logging:
  level:
    web: DEBUG
management:
  endpoints:
    web:
      base-path: "/actuator"
      exposure:
        include:
          - health
          - info
          - mappings
  server:
    port: ${MONITOR_PORT:8081}
server:
  port: ${PORT:8081}
  servlet:
    context-path: "/"
spring:
  application:
    name: circuit-breaker
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: ${PROFILE:local}
feign:
  client:
    config:
      default:
        connection-timeout: 3500
        read-timeout: 3500
      always-fail-client:
        base-url: "http://localhost:8081/stub"
      okhttp-wait-time-client:
        base-url: "http://localhost:8081/stub"
      random-fail-client:
        base-url: "http://localhost:8081/stub"
      succeed-or-fail-client:
        base-url: "http://localhost:8081/stub"
      wait-time-client:
        base-url: "http://localhost:8081/stub"
        connection-timeout: 2500
        read-timeout: 2500
      wait-time-v2-client:
        base-url: "http://localhost:8081/stub"
        connection-timeout: 1500
        read-timeout: 1500
      waitTimeV3Client:
        base-url: "http://localhost:8081/stub"
  httpclient:
    enabled: true
    connection-timeout: 2000
  hystrix:
    enabled: true
  okhttp:
    enabled: false
